// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxcLH63-8hZFkFyrWTimEuZ0kCrvIJm50',
    appId: '1:27269304190:web:beef3208b705a760b5ad2f',
    messagingSenderId: '27269304190',
    projectId: 'kritun-226bd',
    authDomain: 'kritun-226bd.firebaseapp.com',
    storageBucket: 'kritun-226bd.firebasestorage.app',
    measurementId: 'G-0XPH326MG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMIZQ0Hmwt--OLv2t5D6zsEm3JjoAGVMs',
    appId: '1:27269304190:android:54c8009c6a753814b5ad2f',
    messagingSenderId: '27269304190',
    projectId: 'kritun-226bd',
    storageBucket: 'kritun-226bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE4tVFhETF6jDJAkKscqxZaEFjSHZb_gI',
    appId: '1:27269304190:ios:9c5d660a0770b437b5ad2f',
    messagingSenderId: '27269304190',
    projectId: 'kritun-226bd',
    storageBucket: 'kritun-226bd.firebasestorage.app',
    iosBundleId: 'com.example.kritun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE4tVFhETF6jDJAkKscqxZaEFjSHZb_gI',
    appId: '1:27269304190:ios:9c5d660a0770b437b5ad2f',
    messagingSenderId: '27269304190',
    projectId: 'kritun-226bd',
    storageBucket: 'kritun-226bd.firebasestorage.app',
    iosBundleId: 'com.example.kritun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxcLH63-8hZFkFyrWTimEuZ0kCrvIJm50',
    appId: '1:27269304190:web:21ca8c96a3913cb7b5ad2f',
    messagingSenderId: '27269304190',
    projectId: 'kritun-226bd',
    authDomain: 'kritun-226bd.firebaseapp.com',
    storageBucket: 'kritun-226bd.firebasestorage.app',
    measurementId: 'G-HC1Z67FQ3M',
  );
}
